[server]
# サーバー設定
port = 8501
address = "localhost"
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200

# WebSocketの設定
enableWebsocketCompression = true

# ヘルスチェックパスの設定
headless = true

# ベースURLパスの設定
baseUrlPath = ""

[browser]
# ブラウザ自動起動を無効化
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[client]
# クライアント側の設定
showErrorDetails = true
toolbarMode = "auto"

[runner]
# ランナー設定
magicEnabled = true
fastReruns = true

[theme]
# テーマ設定（オプション）
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
