blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/taiyousan15/kindle-text-extraction/blob/main/README.md
    about: Check the project documentation
  - name: Discussions
    url: https://github.com/taiyousan15/kindle-text-extraction/discussions
    about: Ask questions and discuss ideas
