"""add_authentication_fields_to_users

Revision ID: 5aa636e83b69
Revises: d53621f402b5
Create Date: 2025-10-29 14:37:08.730126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aa636e83b69'
down_revision = 'd53621f402b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summaries', sa.Column('format', sa.String(length=50), nullable=True))
    op.add_column('summaries', sa.Column('language', sa.String(length=10), nullable=True))

    # Add authentication columns with temporary nullable to allow existing users
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))

    # Set default values for existing users
    # Use a pre-generated bcrypt hash for password "TEMP_PASS"
    # Generated with: python -c "from passlib.context import CryptContext; print(CryptContext(schemes=['bcrypt']).hash('TEMP_PASS'))"
    default_password_hash = "$2b$12$rHKQv1LxY9QzY.E3D/v3NuLvJvH4ZlMXDqJFKvH5wZ5PQE.6JHZrO"

    op.execute(f"UPDATE users SET hashed_password = '{default_password_hash}' WHERE hashed_password IS NULL")
    op.execute("UPDATE users SET is_active = true WHERE is_active IS NULL")
    op.execute("UPDATE users SET updated_at = created_at WHERE updated_at IS NULL")

    # Now make columns non-nullable
    op.alter_column('users', 'hashed_password', nullable=False)
    op.alter_column('users', 'is_active', nullable=False)
    op.alter_column('users', 'updated_at', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'hashed_password')
    op.drop_column('summaries', 'language')
    op.drop_column('summaries', 'format')
    # ### end Alembic commands ###
