# Prometheus Configuration for Kindle OCR System

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'kindle-ocr'
    environment: 'production'

# Alertmanager configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets: ['alertmanager:9093']

# Load rules
# rule_files:
#   - '/etc/prometheus/rules/*.yml'

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # FastAPI application metrics
  - job_name: 'kindle-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # PostgreSQL metrics (requires postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    # metrics_path: '/metrics'

  # Redis metrics (requires redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    # metrics_path: '/metrics'

  # Celery metrics (requires celery-prometheus-exporter)
  - job_name: 'celery'
    static_configs:
      - targets: ['worker:9090']
    # metrics_path: '/metrics'

  # Node exporter for system metrics (if deployed)
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['node-exporter:9100']

  # Docker metrics (if using cAdvisor)
  # - job_name: 'docker'
  #   static_configs:
  #     - targets: ['cadvisor:8080']
